name: GUI
version: 1.0
description: GUI-cmd
author: Fredie1104
authors: [Fredie1104, joestr]

main: de.fredie.gui.main.Main
database: false
#depend: [Alpha-01]

commands:
  gui:
    description: Oeffnet das GUI-Menue.
    #permission: command.gui
    #permission-message: Berechtigung command.gui fehlt.
    usage: /gui